
  name: naomi
  version: '2.2' # just for humans, typically '1.2+git' or '1.3.2'
  summary: open source platform for developing always-on, voice-controlled applications
  description: |
    an open source platform for developing always-on, voice-controlled applications.

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    naomi:
      # See 'snapcraft plugins'
      plugin: python
  
