name: 'Nightly Publish'

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  nightly-publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Nightly Publish
      env:
        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
      run: |
        git clone https://github.com/NaomiProject/Naomi.git
        cd ~/Naomi
        git checkout naomi-dev
        git pull
        cd ~
        mv Naomi Naomi-Nightly
        zip -r Naomi-Nightly.zip Naomi-Nightly
        curl -T Naomi-Nightly.zip -uabcasteel:${{ secrets.BINTRAY_KEY }} https://api.bintray.com/content/naomiproject/rpi-repo2/Naomi/Nightly/
        curl -X POST -uabcasteel:${{ secrets.BINTRAY_KEY }} https://api.bintray.com/content/naomiproject/rpi-repo2/Naomi/Nightly/Publish
